artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  kaggle_dataset: mexwell/gym-check-ins-and-user-metadata
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion